version: 0.2

phases:
  install:
    commands:
      - echo Entering src directory...
      - cd src
      - npm install
  build:
    commands:
      - cd src
      - npm run build

artifacts:
  files:
    - '**/*'
